AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  test-api-gateway

  Sample SAM Template for test-api-gateway
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Parameters:
  slackToken:
    Description: Env
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: /config/global/slack-token
  channelId:
    Description: Env
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: /config/global/channel-id

Resources:
  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:*"
                Resource: "*"
  ApiPetsStore:
    Type: AWS::Serverless::Api
    Properties:
      StageName: test
      DefinitionUri: ./petstore.json

  ApiTest:
    Type: AWS::Serverless::Api
    Properties:
      StageName: test
      DefinitionUri: ./test.json

  ApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 61
      FunctionName: smartpagApi
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Api:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1
            Method: get

  NotificationSlackFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 62
      FunctionName: smartpagNotificationSlack
      CodeUri: src/
      Handler: slack.lambdaHandler
      Runtime: nodejs12.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          SLACK_TOKEN: !Ref slackToken
          CHANNEL_ID: !Ref channelId
      Events:
        DTISchedule:
          Type: Schedule
          Properties:
            Schedule: rate(2 hours)
            Name: smartpag-notification-slack
            Description: Job de base do polling
            Enabled: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage for Api function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/v1/"
  ApiFunction:
    Description: "Api Lambda Function ARN"
    Value: !GetAtt ApiFunction.Arn
